# This is a basic workflow to help you get started with Actions

name: Simple workflow

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.step1_out }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        id: step1
        run: echo "step1_out=Hello, world!" >> $GITHUB_OUTPUT

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        id: step2
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          echo ${{ build.outputs.output1 }}
